<?php

use Illuminate\Database\Seeder;

class IndemnityPlaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$this->insertDataProvince();
    	$this->insertDataDistrict();
    }

    public function insertDataProvince() {
    	$data = [["code" => "AGI", "name" => "An Giang"],
    	["code" => "BRI", "name" => "Bà Rịa Vũng Tàu"],
    	["code" => "BGI", "name" => "Bắc Giang"],
    	["code" => "BKA", "name" => "Bắc Kạn"],
    	["code" => "BLI", "name" => "Bạc Liêu"],
    	["code" => "BNI", "name" => "Bắc Ninh"],
    	["code" => "BTR", "name" => "Bến Tre"],
    	["code" => "BID", "name" => "Bình Ðịnh"],
    	["code" => "BDI", "name" => "Bình Dương"],
    	["code" => "BPH", "name" => "Bình Phước"],
    	["code" => "BTH", "name" => "Bình Thuận"],
    	["code" => "CMA", "name" => "Cà Mau"],
    	["code" => "CTH", "name" => "Cần Thơ"],
    	["code" => "CBA", "name" => "Cao Bằng"],
    	["code" => "DNG", "name" => "Ðà Nẵng"],
    	["code" => "DAK", "name" => "Ðak Lak"],
    	["code" => "DKN", "name" => "Đắk Nông"],
    	["code" => "DBI", "name" => "Ðiện Biên"],
    	["code" => "DNA", "name" => "Ðồng Nai"],
    	["code" => "DTH", "name" => "Ðồng Tháp"],
    	["code" => "GLA", "name" => "Gia Lai"],
    	["code" => "HGI", "name" => "Hà Giang"],
    	["code" => "HNA", "name" => "Hà Nam"],
    	["code" => "HNO", "name" => "Hà Nội"],
    	["code" => "HTA", "name" => "Hà Tây"],
    	["code" => "HTI", "name" => "Hà Tĩnh"],
    	["code" => "HDU", "name" => "Hải Dương"],
    	["code" => "HPO", "name" => "Hải Phòng"],
    	["code" => "HUG", "name" => "Hậu Giang"],
    	["code" => "HBI", "name" => "Hòa Bình"],
    	["code" => "HYE", "name" => "Hưng Yên"],
    	["code" => "KHO", "name" => "Khánh Hòa"],
    	["code" => "MB", "name" => "Khu vực Miền Bắc"],
    	["code" => "MN", "name" => "Khu vực Miền Nam"],
    	["code" => "MT", "name" => "Khu vực Miền Trung"],
    	["code" => "KGI", "name" => "Kiên Giang"],
    	["code" => "KON", "name" => "Kon Tum"],
    	["code" => "LCH", "name" => "Lai Châu"],
    	["code" => "LDO", "name" => "Lâm Ðồng"],
    	["code" => "LSO", "name" => "Lạng Sơn"],
    	["code" => "LCA", "name" => "Lào  Cai"],
    	["code" => "LAN", "name" => "Long An"],
    	["code" => "NDI", "name" => "Nam Ðịnh"],
    	["code" => "NAN", "name" => "Nghệ An"],
    	["code" => "NBI", "name" => "Ninh Bình"],
    	["code" => "NTH", "name" => "Ninh Thuận"],
    	["code" => "OVERSEA", "name" => "Nước ngoài"],
    	["code" => "PTO", "name" => "Phú Thọ"],
    	["code" => "PYE", "name" => "Phú Yên"],
    	["code" => "QBI", "name" => "Quảng Bình"],
    	["code" => "QNA", "name" => "Quảng Nam"],
    	["code" => "QNG", "name" => "Quảng Ngãi"],
    	["code" => "QNI", "name" => "Quảng Ninh"],
    	["code" => "QTI", "name" => "Quảng Trị"],
    	["code" => "STR", "name" => "Sóc Trăng"],
    	["code" => "SLA", "name" => "Son La"],
    	["code" => "TNI", "name" => "Tây Ninh"],
    	["code" => "TBI", "name" => "Thái Bình"],
    	["code" => "TNG", "name" => "Thái Nguyên"],
    	["code" => "THO", "name" => "Thanh Hóa"],
    	["code" => "TTH", "name" => "Thừa Thiên Huế"],
    	["code" => "TGI", "name" => "Tiền Giang"],
    	["code" => "HCM", "name" => "TP Hồ Chí Minh"],
    	["code" => "TVI", "name" => "Trà Vinh"],
    	["code" => "TQU", "name" => "Tuyên Quang"],
    	["code" => "VIE", "name" => "Việt Nam"],
    	["code" => "VLO", "name" => "Vinh Long"],
    	["code" => "VPH", "name" => "Vinh Phúc"],
    	["code" => "YBA", "name" => "Yên Bái"]];

    	DB::table('indemnity_provinces')->insert($data);
    }

    public function insertDataDistrict() {
    	$data = [["code" => "859", "name" => "Huyện  Vũng Liêm", "province_code" => "VLO"],
    	["code" => "481", "name" => "Huyện A Lưới", "province_code" => "TTH"],
    	["code" => "908", "name" => "Huyện An Biên", "province_code" => "KGI"],
    	["code" => "312", "name" => "Huyện An Dương", "province_code" => "HPO"],
    	["code" => "542", "name" => "Huyện An Lão", "province_code" => "BID"],
    	["code" => "313", "name" => "Huyện An Lão", "province_code" => "HPO"],
    	["code" => "909", "name" => "Huyện An Minh", "province_code" => "KGI"],
    	["code" => "886", "name" => "Huyện An Phú", "province_code" => "AGI"],
    	["code" => "329", "name" => "Huyện Ân Thi", "province_code" => "HYE"],
    	["code" => "424", "name" => "Huyện Anh Sơn", "province_code" => "NAN"],
    	["code" => "061", "name" => "Huyện Ba Bể", "province_code" => "BKA"],
    	["code" => "202", "name" => "Huyện Ba Chẽ", "province_code" => "QNI"],
    	["code" => "386", "name" => "Huyện Bá Thước", "province_code" => "THO"],
    	["code" => "535", "name" => "Huyện Ba Tơ", "province_code" => "QNG"],
    	["code" => "836", "name" => "Huyện Ba Tri", "province_code" => "BTR"],
    	["code" => "271", "name" => "Huyện Ba Vì", "province_code" => "HNO"],
    	["code" => "584", "name" => "Huyện Bác Ái", "province_code" => "NTH"],
    	["code" => "596", "name" => "Huyện Bắc Bình", "province_code" => "BTH"],
    	["code" => "085", "name" => "Huyện Bắc Hà", "province_code" => "LCA"],
    	["code" => "031", "name" => "Huyện Bắc Mê", "province_code" => "HGI"],
    	["code" => "034", "name" => "Huyện Bắc Quang", "province_code" => "HGI"],
    	["code" => "185", "name" => "Huyện Bắc Sơn", "province_code" => "LSO"],
    	["code" => "726", "name" => "Huyện Bắc Tân Uyên", "province_code" => "BDI"],
    	["code" => "515", "name" => "Huyện Bắc Trà My", "province_code" => "QNA"],
    	["code" => "121", "name" => "Huyện Bắc Yên", "province_code" => "SLA"],
    	["code" => "318", "name" => "Huyện Bạch Long Vĩ", "province_code" => "HPO"],
    	["code" => "063", "name" => "Huyện Bạch Thông", "province_code" => "BKA"],
    	["code" => "043", "name" => "Huyện Bảo Lạc", "province_code" => "CBA"],
    	["code" => "680", "name" => "Huyện Bảo Lâm", "province_code" => "LDO"],
    	["code" => "042", "name" => "Huyện Bảo Lâm", "province_code" => "CBA"],
    	["code" => "086", "name" => "Huyện Bảo Thắng", "province_code" => "LCA"],
    	["code" => "087", "name" => "Huyện Bảo Yên", "province_code" => "LCA"],
    	["code" => "082", "name" => "Huyện Bát Xát", "province_code" => "LCA"],
    	["code" => "719", "name" => "Huyện Bàu Bàng", "province_code" => "BDI"],
    	["code" => "711", "name" => "Huyện Bến Cầu", "province_code" => "TNI"],
    	["code" => "803", "name" => "Huyện Bến Lức", "province_code" => "LAN"],
    	["code" => "785", "name" => "Huyện Bình Chánh", "province_code" => "HCM"],
    	["code" => "835", "name" => "Huyện Bình Đại", "province_code" => "BTR"],
    	["code" => "181", "name" => "Huyện Bình Gia", "province_code" => "LSO"],
    	["code" => "296", "name" => "Huyện Bình Giang", "province_code" => "HDU"],
    	["code" => "198", "name" => "Huyện Bình Liêu", "province_code" => "QNI"],
    	["code" => "352", "name" => "Huyện Bình Lục", "province_code" => "HNA"],
    	["code" => "524", "name" => "Huyện Bình Sơn", "province_code" => "QNG"],
    	["code" => "863", "name" => "Huyện Bình Tân", "province_code" => "VLO"],
    	["code" => "249", "name" => "Huyện Bình Xuyên", "province_code" => "VPH"],
    	["code" => "455", "name" => "Huyện Bố Trạch", "province_code" => "QBI"],
    	["code" => "696", "name" => "Huyện Bù Đăng", "province_code" => "BPH"],
    	["code" => "693", "name" => "Huyện Bù Đốp", "province_code" => "BPH"],
    	["code" => "691", "name" => "Huyện Bù Gia Mập", "province_code" => "BPH"],
    	["code" => "647", "name" => "Huyện Buôn Đôn", "province_code" => "DAK"],
    	["code" => "819", "name" => "Huyện Cái Bè", "province_code" => "TGI"],
    	["code" => "820", "name" => "Huyện Cai Lậy", "province_code" => "TGI"],
    	["code" => "969", "name" => "Huyện Cái Nước", "province_code" => "CMA"],
    	["code" => "295", "name" => "Huyện Cẩm Giàng", "province_code" => "HDU"],
    	["code" => "235", "name" => "Huyện Cẩm Khê", "province_code" => "PTO"],
    	["code" => "570", "name" => "Huyện Cam Lâm", "province_code" => "KHO"],
    	["code" => "468", "name" => "Huyện Cam Lộ", "province_code" => "QTI"],
    	["code" => "739", "name" => "Huyện Cẩm Mỹ", "province_code" => "DNA"],
    	["code" => "390", "name" => "Huyện Cẩm Thủy", "province_code" => "THO"],
    	["code" => "446", "name" => "Huyện Cẩm Xuyên", "province_code" => "HTI"],
    	["code" => "806", "name" => "Huyện Cần Đước", "province_code" => "LAN"],
    	["code" => "787", "name" => "Huyện Cần Giờ", "province_code" => "HCM"],
    	["code" => "807", "name" => "Huyện Cần Giuộc", "province_code" => "LAN"],
    	["code" => "443", "name" => "Huyện Can Lộc", "province_code" => "HTI"],
    	["code" => "844", "name" => "Huyện Càng Long", "province_code" => "TVI"],
    	["code" => "873", "name" => "Huyện Cao Lãnh", "province_code" => "DTH"],
    	["code" => "183", "name" => "Huyện Cao Lộc", "province_code" => "LSO"],
    	["code" => "154", "name" => "Huyện Cao Phong", "province_code" => "HBI"],
    	["code" => "317", "name" => "Huyện Cát Hải", "province_code" => "HPO"],
    	["code" => "683", "name" => "Huyện Cát Tiên", "province_code" => "LDO"],
    	["code" => "845", "name" => "Huyện Cầu Kè", "province_code" => "TVI"],
    	["code" => "848", "name" => "Huyện Cầu Ngang", "province_code" => "TVI"],
    	["code" => "750", "name" => "Huyện Châu Đức", "province_code" => "BRI"],
    	["code" => "889", "name" => "Huyện Châu Phú", "province_code" => "AGI"],
    	["code" => "877", "name" => "Huyện Châu Thành", "province_code" => "DTH"],
    	["code" => "821", "name" => "Huyện Châu Thành", "province_code" => "TGI"],
    	["code" => "847", "name" => "Huyện Châu Thành", "province_code" => "TVI"],
    	["code" => "892", "name" => "Huyện Châu Thành", "province_code" => "AGI"],
    	["code" => "808", "name" => "Huyện Châu Thành", "province_code" => "LAN"],
    	["code" => "942", "name" => "Huyện Châu Thành", "province_code" => "STR"],
    	["code" => "933", "name" => "Huyện Châu Thành", "province_code" => "HUG"],
    	["code" => "831", "name" => "Huyện Châu Thành", "province_code" => "BTR"],
    	["code" => "905", "name" => "Huyện Châu Thành", "province_code" => "KGI"],
    	["code" => "708", "name" => "Huyện Châu Thành", "province_code" => "TNI"],
    	["code" => "932", "name" => "Huyện Châu Thành A", "province_code" => "HUG"],
    	["code" => "187", "name" => "Huyện Chi Lăng", "province_code" => "LSO"],
    	["code" => "073", "name" => "Huyện Chiêm Hóa", "province_code" => "TQU"],
    	["code" => "064", "name" => "Huyện Chợ Đồn", "province_code" => "BKA"],
    	["code" => "822", "name" => "Huyện Chợ Gạo", "province_code" => "TGI"],
    	["code" => "832", "name" => "Huyện Chợ Lách", "province_code" => "BTR"],
    	["code" => "893", "name" => "Huyện Chợ Mới", "province_code" => "AGI"],
    	["code" => "065", "name" => "Huyện Chợ Mới", "province_code" => "BKA"],
    	["code" => "697", "name" => "Huyện Chơn Thành", "province_code" => "BPH"],
    	["code" => "627", "name" => "Huyện Chư Păh", "province_code" => "GLA"],
    	["code" => "632", "name" => "Huyện Chư Prông", "province_code" => "GLA"],
    	["code" => "639", "name" => "Huyện Chư Pưh", "province_code" => "GLA"],
    	["code" => "633", "name" => "Huyện Chư Sê", "province_code" => "GLA"],
    	["code" => "277", "name" => "Huyện Chương Mỹ", "province_code" => "HNO"],
    	["code" => "925", "name" => "Huyện Cờ Đỏ", "province_code" => "CTH"],
    	["code" => "207", "name" => "Huyện Cô Tô", "province_code" => "QNI"],
    	["code" => "471", "name" => "Huyện Cồn Cỏ", "province_code" => "QTI"],
    	["code" => "422", "name" => "Huyện Con Cuông", "province_code" => "NAN"],
    	["code" => "755", "name" => "Huyện Côn Đảo", "province_code" => "BRI"],
    	["code" => "783", "name" => "Huyện Củ Chi", "province_code" => "HCM"],
    	["code" => "662", "name" => "Huyện Cư Jút", "province_code" => "DKN"],
    	["code" => "657", "name" => "Huyện Cư Kuin", "province_code" => "DAK"],
    	["code" => "945", "name" => "Huyện Cù Lao Dung", "province_code" => "STR"],
    	["code" => "648", "name" => "Huyện Cư M'gar", "province_code" => "DAK"],
    	["code" => "150", "name" => "Huyện Đà Bắc", "province_code" => "HBI"],
    	["code" => "681", "name" => "Huyện Đạ Huoai", "province_code" => "LDO"],
    	["code" => "467", "name" => "Huyện Đa Krông", "province_code" => "QTI"],
    	["code" => "682", "name" => "Huyện Đạ Tẻh", "province_code" => "LDO"],
    	["code" => "506", "name" => "Huyện Đại Lộc", "province_code" => "QNA"],
    	["code" => "171", "name" => "Huyện Đại Từ", "province_code" => "TNG"],
    	["code" => "626", "name" => "Huyện Đăk Đoa", "province_code" => "GLA"],
    	["code" => "610", "name" => "Huyện Đắk Glei", "province_code" => "KON"],
    	["code" => "661", "name" => "Huyện Đăk Glong", "province_code" => "DKN"],
    	["code" => "615", "name" => "Huyện Đắk Hà", "province_code" => "KON"],
    	["code" => "663", "name" => "Huyện Đắk Mil", "province_code" => "DKN"],
    	["code" => "634", "name" => "Huyện Đăk Pơ", "province_code" => "GLA"],
    	["code" => "666", "name" => "Huyện Đắk R'Lấp", "province_code" => "DKN"],
    	["code" => "665", "name" => "Huyện Đắk Song", "province_code" => "DKN"],
    	["code" => "612", "name" => "Huyện Đắk Tô", "province_code" => "KON"],
    	["code" => "970", "name" => "Huyện Đầm Dơi", "province_code" => "CMA"],
    	["code" => "200", "name" => "Huyện Đầm Hà", "province_code" => "QNI"],
    	["code" => "674", "name" => "Huyện Đam Rông", "province_code" => "LDO"],
    	["code" => "273", "name" => "Huyện Đan Phượng", "province_code" => "HNO"],
    	["code" => "753", "name" => "Huyện Đất Đỏ", "province_code" => "BRI"],
    	["code" => "720", "name" => "Huyện Dầu Tiếng", "province_code" => "BDI"],
    	["code" => "679", "name" => "Huyện Di Linh", "province_code" => "LDO"],
    	["code" => "100", "name" => "Huyện Điện Biên", "province_code" => "DBI"],
    	["code" => "101", "name" => "Huyện Điện Biên Đông", "province_code" => "DBI"],
    	["code" => "425", "name" => "Huyện Diễn Châu", "province_code" => "NAN"],
    	["code" => "574", "name" => "Huyện Diên Khánh", "province_code" => "KHO"],
    	["code" => "167", "name" => "Huyện Định Hóa", "province_code" => "TNG"],
    	["code" => "189", "name" => "Huyện Đình Lập", "province_code" => "LSO"],
    	["code" => "736", "name" => "Huyện Định Quán", "province_code" => "DNA"],
    	["code" => "427", "name" => "Huyện Đô Lương", "province_code" => "NAN"],
    	["code" => "230", "name" => "Huyện Đoan Hùng", "province_code" => "PTO"],
    	["code" => "677", "name" => "Huyện Đơn Dương", "province_code" => "LDO"],
    	["code" => "017", "name" => "Huyện Đông Anh", "province_code" => "HNO"],
    	["code" => "505", "name" => "Huyện Đông Giang", "province_code" => "QNA"],
    	["code" => "960", "name" => "Huyện Đông Hải", "province_code" => "BLI"],
    	["code" => "564", "name" => "Huyện Đông Hòa", "province_code" => "PYE"],
    	["code" => "340", "name" => "Huyện Đông Hưng", "province_code" => "TBI"],
    	["code" => "169", "name" => "Huyện Đồng Hỷ", "province_code" => "TNG"],
    	["code" => "695", "name" => "Huyện Đồng Phú", "province_code" => "BPH"],
    	["code" => "405", "name" => "Huyện Đông Sơn", "province_code" => "THO"],
    	["code" => "026", "name" => "Huyện Đồng Văn", "province_code" => "HGI"],
    	["code" => "558", "name" => "Huyện Đồng Xuân", "province_code" => "PYE"],
    	["code" => "631", "name" => "Huyện Đức Cơ", "province_code" => "GLA"],
    	["code" => "802", "name" => "Huyện Đức Hòa", "province_code" => "LAN"],
    	["code" => "801", "name" => "Huyện Đức Huệ", "province_code" => "LAN"],
    	["code" => "600", "name" => "Huyện Đức Linh", "province_code" => "BTH"],
    	["code" => "534", "name" => "Huyện Đức Phổ", "province_code" => "QNG"],
    	["code" => "440", "name" => "Huyện Đức Thọ", "province_code" => "HTI"],
    	["code" => "678", "name" => "Huyện Đức Trọng", "province_code" => "LDO"],
    	["code" => "707", "name" => "Huyện Dương Minh Châu", "province_code" => "TNI"],
    	["code" => "349", "name" => "Huyện Duy Tiên", "province_code" => "HNA"],
    	["code" => "508", "name" => "Huyện Duy Xuyên", "province_code" => "QNA"],
    	["code" => "850", "name" => "Huyện Duyên Hải", "province_code" => "TVI"],
    	["code" => "645", "name" => "Huyện Ea H'leo", "province_code" => "DAK"],
    	["code" => "651", "name" => "Huyện Ea Kar", "province_code" => "DAK"],
    	["code" => "646", "name" => "Huyện Ea Súp", "province_code" => "DAK"],
    	["code" => "263", "name" => "Huyện Gia Bình", "province_code" => "BNI"],
    	["code" => "018", "name" => "Huyện Gia Lâm", "province_code" => "HNO"],
    	["code" => "297", "name" => "Huyện Gia Lộc", "province_code" => "HDU"],
    	["code" => "373", "name" => "Huyện Gia Viễn", "province_code" => "NBI"],
    	["code" => "914", "name" => "Huyện Giang Thành", "province_code" => "KGI"],
    	["code" => "365", "name" => "Huyện Giao Thủy", "province_code" => "NDI"],
    	["code" => "466", "name" => "Huyện Gio Linh", "province_code" => "QTI"],
    	["code" => "906", "name" => "Huyện Giồng Riềng", "province_code" => "KGI"],
    	["code" => "834", "name" => "Huyện Giồng Trôm", "province_code" => "BTR"],
    	["code" => "824", "name" => "Huyện Gò Công Đông", "province_code" => "TGI"],
    	["code" => "823", "name" => "Huyện Gò Công Tây", "province_code" => "TGI"],
    	["code" => "710", "name" => "Huyện Gò Dầu", "province_code" => "TNI"],
    	["code" => "907", "name" => "Huyện Gò Quao", "province_code" => "KGI"],
    	["code" => "231", "name" => "Huyện Hạ Hoà", "province_code" => "PTO"],
    	["code" => "048", "name" => "Huyện Hạ Lang", "province_code" => "CBA"],
    	["code" => "045", "name" => "Huyện Hà Quảng", "province_code" => "CBA"],
    	["code" => "392", "name" => "Huyện Hà Trung", "province_code" => "THO"],
    	["code" => "201", "name" => "Huyện Hải Hà", "province_code" => "QNI"],
    	["code" => "366", "name" => "Huyện Hải Hậu", "province_code" => "NDI"],
    	["code" => "470", "name" => "Huyện Hải Lăng", "province_code" => "QTI"],
    	["code" => "601", "name" => "Huyện Hàm Tân", "province_code" => "BTH"],
    	["code" => "597", "name" => "Huyện Hàm Thuận Bắc", "province_code" => "BTH"],
    	["code" => "598", "name" => "Huyện Hàm Thuận Nam", "province_code" => "BTH"],
    	["code" => "074", "name" => "Huyện Hàm Yên", "province_code" => "TQU"],
    	["code" => "400", "name" => "Huyện Hậu Lộc", "province_code" => "THO"],
    	["code" => "512", "name" => "Huyện Hiệp Đức", "province_code" => "QNA"],
    	["code" => "223", "name" => "Huyện Hiệp Hòa", "province_code" => "BGI"],
    	["code" => "051", "name" => "Huyện Hoà An", "province_code" => "CBA"],
    	["code" => "961", "name" => "Huyện Hoà Bình", "province_code" => "BLI"],
    	["code" => "374", "name" => "Huyện Hoa Lư", "province_code" => "NBI"],
    	["code" => "709", "name" => "Huyện Hòa Thành", "province_code" => "TNI"],
    	["code" => "497", "name" => "Huyện Hòa Vang", "province_code" => "DNG"],
    	["code" => "544", "name" => "Huyện Hoài Ân", "province_code" => "BID"],
    	["code" => "274", "name" => "Huyện Hoài Đức", "province_code" => "HNO"],
    	["code" => "543", "name" => "Huyện Hoài Nhơn", "province_code" => "BID"],
    	["code" => "399", "name" => "Huyện Hoằng Hóa", "province_code" => "THO"],
    	["code" => "498", "name" => "Huyện Hoàng Sa", "province_code" => "DNG"],
    	["code" => "032", "name" => "Huyện Hoàng Su Phì", "province_code" => "HGI"],
    	["code" => "204", "name" => "Huyện Hoành Bồ", "province_code" => "QNI"],
    	["code" => "784", "name" => "Huyện Hóc Môn", "province_code" => "HCM"],
    	["code" => "903", "name" => "Huyện Hòn Đất", "province_code" => "KGI"],
    	["code" => "694", "name" => "Huyện Hớn Quản", "province_code" => "BPH"],
    	["code" => "956", "name" => "Huyện Hồng Dân", "province_code" => "BLI"],
    	["code" => "870", "name" => "Huyện Hồng Ngự", "province_code" => "DTH"],
    	["code" => "339", "name" => "Huyện Hưng Hà", "province_code" => "TBI"],
    	["code" => "431", "name" => "Huyện Hưng Nguyên", "province_code" => "NAN"],
    	["code" => "465", "name" => "Huyện Hướng Hóa", "province_code" => "QTI"],
    	["code" => "444", "name" => "Huyện Hương Khê", "province_code" => "HTI"],
    	["code" => "439", "name" => "Huyện Hương Sơn", "province_code" => "HTI"],
    	["code" => "186", "name" => "Huyện Hữu Lũng", "province_code" => "LSO"],
    	["code" => "628", "name" => "Huyện Ia Grai", "province_code" => "GLA"],
    	["code" => "618", "name" => "Huyện Ia H' Drai", "province_code" => "KON"],
    	["code" => "635", "name" => "Huyện Ia Pa", "province_code" => "GLA"],
    	["code" => "625", "name" => "Huyện KBang", "province_code" => "GLA"],
    	["code" => "943", "name" => "Huyện Kế Sách", "province_code" => "STR"],
    	["code" => "575", "name" => "Huyện Khánh Sơn", "province_code" => "KHO"],
    	["code" => "573", "name" => "Huyện Khánh Vĩnh", "province_code" => "KHO"],
    	["code" => "330", "name" => "Huyện Khoái Châu", "province_code" => "HYE"],
    	["code" => "912", "name" => "Huyện Kiên Hải", "province_code" => "KGI"],
    	["code" => "902", "name" => "Huyện Kiên Lương", "province_code" => "KGI"],
    	["code" => "314", "name" => "Huyện Kiến Thuỵ", "province_code" => "HPO"],
    	["code" => "343", "name" => "Huyện Kiến Xương", "province_code" => "TBI"],
    	["code" => "350", "name" => "Huyện Kim Bảng", "province_code" => "HNA"],
    	["code" => "153", "name" => "Huyện Kim Bôi", "province_code" => "HBI"],
    	["code" => "331", "name" => "Huyện Kim Động", "province_code" => "HYE"],
    	["code" => "376", "name" => "Huyện Kim Sơn", "province_code" => "NBI"],
    	["code" => "293", "name" => "Huyện Kim Thành", "province_code" => "HDU"],
    	["code" => "292", "name" => "Huyện Kinh Môn", "province_code" => "HDU"],
    	["code" => "613", "name" => "Huyện Kon Plông", "province_code" => "KON"],
    	["code" => "614", "name" => "Huyện Kon Rẫy", "province_code" => "KON"],
    	["code" => "630", "name" => "Huyện Kông Chro", "province_code" => "GLA"],
    	["code" => "655", "name" => "Huyện Krông A Na", "province_code" => "DAK"],
    	["code" => "653", "name" => "Huyện Krông Bông", "province_code" => "DAK"],
    	["code" => "649", "name" => "Huyện Krông Búk", "province_code" => "DAK"],
    	["code" => "650", "name" => "Huyện Krông Năng", "province_code" => "DAK"],
    	["code" => "664", "name" => "Huyện Krông Nô", "province_code" => "DKN"],
    	["code" => "637", "name" => "Huyện Krông Pa", "province_code" => "GLA"],
    	["code" => "654", "name" => "Huyện Krông Pắc", "province_code" => "DAK"],
    	["code" => "447", "name" => "Huyện Kỳ Anh", "province_code" => "HTI"],
    	["code" => "417", "name" => "Huyện Kỳ Sơn", "province_code" => "NAN"],
    	["code" => "151", "name" => "Huyện Kỳ Sơn", "province_code" => "HBI"],
    	["code" => "675", "name" => "Huyện Lạc Dương", "province_code" => "LDO"],
    	["code" => "157", "name" => "Huyện Lạc Sơn", "province_code" => "HBI"],
    	["code" => "159", "name" => "Huyện Lạc Thủy", "province_code" => "HBI"],
    	["code" => "876", "name" => "Huyện Lai Vung", "province_code" => "DTH"],
    	["code" => "656", "name" => "Huyện Lắk", "province_code" => "DAK"],
    	["code" => "071", "name" => "Huyện Lâm Bình", "province_code" => "TQU"],
    	["code" => "676", "name" => "Huyện Lâm Hà", "province_code" => "LDO"],
    	["code" => "237", "name" => "Huyện Lâm Thao", "province_code" => "PTO"],
    	["code" => "388", "name" => "Huyện Lang Chánh", "province_code" => "THO"],
    	["code" => "217", "name" => "Huyện Lạng Giang", "province_code" => "BGI"],
    	["code" => "246", "name" => "Huyện Lập Thạch", "province_code" => "VPH"],
    	["code" => "875", "name" => "Huyện Lấp Vò", "province_code" => "DTH"],
    	["code" => "457", "name" => "Huyện Lệ Thủy", "province_code" => "QBI"],
    	["code" => "188", "name" => "Huyện Lộc Bình", "province_code" => "LSO"],
    	["code" => "448", "name" => "Huyện Lộc Hà", "province_code" => "HTI"],
    	["code" => "692", "name" => "Huyện Lộc Ninh", "province_code" => "BPH"],
    	["code" => "752", "name" => "Huyện Long Điền", "province_code" => "BRI"],
    	["code" => "857", "name" => "Huyện Long Hồ", "province_code" => "VLO"],
    	["code" => "936", "name" => "Huyện Long Mỹ", "province_code" => "HUG"],
    	["code" => "946", "name" => "Huyện Long Phú", "province_code" => "STR"],
    	["code" => "740", "name" => "Huyện Long Thành", "province_code" => "DNA"],
    	["code" => "218", "name" => "Huyện Lục Nam", "province_code" => "BGI"],
    	["code" => "219", "name" => "Huyện Lục Ngạn", "province_code" => "BGI"],
    	["code" => "135", "name" => "Huyện Lục Yên", "province_code" => "YBA"],
    	["code" => "152", "name" => "Huyện Lương Sơn", "province_code" => "HBI"],
    	["code" => "264", "name" => "Huyện Lương Tài", "province_code" => "BNI"],
    	["code" => "353", "name" => "Huyện Lý Nhân", "province_code" => "HNA"],
    	["code" => "536", "name" => "Huyện Lý Sơn", "province_code" => "QNG"],
    	["code" => "156", "name" => "Huyện Mai Châu", "province_code" => "HBI"],
    	["code" => "125", "name" => "Huyện Mai Sơn", "province_code" => "SLA"],
    	["code" => "858", "name" => "Huyện Mang Thít", "province_code" => "VLO"],
    	["code" => "629", "name" => "Huyện Mang Yang", "province_code" => "GLA"],
    	["code" => "652", "name" => "Huyện M'Đrắk", "province_code" => "DAK"],
    	["code" => "250", "name" => "Huyện Mê Linh", "province_code" => "HNO"],
    	["code" => "027", "name" => "Huyện Mèo Vạc", "province_code" => "HGI"],
    	["code" => "452", "name" => "Huyện Minh Hóa", "province_code" => "QBI"],
    	["code" => "531", "name" => "Huyện Minh Long", "province_code" => "QNG"],
    	["code" => "838", "name" => "Huyện Mỏ Cày Bắc", "province_code" => "BTR"],
    	["code" => "833", "name" => "Huyện Mỏ Cày Nam", "province_code" => "BTR"],
    	["code" => "533", "name" => "Huyện Mộ Đức", "province_code" => "QNG"],
    	["code" => "123", "name" => "Huyện Mộc Châu", "province_code" => "SLA"],
    	["code" => "798", "name" => "Huyện Mộc Hóa", "province_code" => "LAN"],
    	["code" => "137", "name" => "Huyện Mù Căng Chải", "province_code" => "YBA"],
    	["code" => "102", "name" => "Huyện Mường Ảng", "province_code" => "DBI"],
    	["code" => "097", "name" => "Huyện Mường Chà", "province_code" => "DBI"],
    	["code" => "083", "name" => "Huyện Mường Khương", "province_code" => "LCA"],
    	["code" => "120", "name" => "Huyện Mường La", "province_code" => "SLA"],
    	["code" => "384", "name" => "Huyện Mường Lát", "province_code" => "THO"],
    	["code" => "096", "name" => "Huyện Mường Nhé", "province_code" => "DBI"],
    	["code" => "107", "name" => "Huyện Mường Tè", "province_code" => "LCH"],
    	["code" => "282", "name" => "Huyện Mỹ Đức", "province_code" => "HNO"],
    	["code" => "328", "name" => "Huyện Mỹ Hào", "province_code" => "HYE"],
    	["code" => "358", "name" => "Huyện Mỹ Lộc", "province_code" => "NDI"],
    	["code" => "944", "name" => "Huyện Mỹ Tú", "province_code" => "STR"],
    	["code" => "947", "name" => "Huyện Mỹ Xuyên", "province_code" => "STR"],
    	["code" => "072", "name" => "Huyện Nà Hang", "province_code" => "TQU"],
    	["code" => "066", "name" => "Huyện Na Rì", "province_code" => "BKA"],
    	["code" => "971", "name" => "Huyện Năm Căn", "province_code" => "CMA"],
    	["code" => "430", "name" => "Huyện Nam Đàn", "province_code" => "NAN"],
    	["code" => "483", "name" => "Huyện Nam Đông", "province_code" => "TTH"],
    	["code" => "510", "name" => "Huyện Nam Giang", "province_code" => "QNA"],
    	["code" => "112", "name" => "Huyện Nậm Nhùn", "province_code" => "LCH"],
    	["code" => "103", "name" => "Huyện Nậm Pồ", "province_code" => "DBI"],
    	["code" => "291", "name" => "Huyện Nam Sách", "province_code" => "HDU"],
    	["code" => "516", "name" => "Huyện Nam Trà My", "province_code" => "QNA"],
    	["code" => "362", "name" => "Huyện Nam Trực", "province_code" => "NDI"],
    	["code" => "401", "name" => "Huyện Nga Sơn", "province_code" => "THO"],
    	["code" => "062", "name" => "Huyện Ngân Sơn", "province_code" => "BKA"],
    	["code" => "429", "name" => "Huyện Nghi Lộc", "province_code" => "NAN"],
    	["code" => "442", "name" => "Huyện Nghi Xuân", "province_code" => "HTI"],
    	["code" => "419", "name" => "Huyện Nghĩa Đàn", "province_code" => "NAN"],
    	["code" => "532", "name" => "Huyện Nghĩa Hành", "province_code" => "QNG"],
    	["code" => "361", "name" => "Huyện Nghĩa Hưng", "province_code" => "NDI"],
    	["code" => "973", "name" => "Huyện Ngọc Hiển", "province_code" => "CMA"],
    	["code" => "611", "name" => "Huyện Ngọc Hồi", "province_code" => "KON"],
    	["code" => "389", "name" => "Huyện Ngọc Lặc", "province_code" => "THO"],
    	["code" => "052", "name" => "Huyện Nguyên Bình", "province_code" => "CBA"],
    	["code" => "786", "name" => "Huyện Nhà Bè", "province_code" => "HCM"],
    	["code" => "372", "name" => "Huyện Nho Quan", "province_code" => "NBI"],
    	["code" => "742", "name" => "Huyện Nhơn Trạch", "province_code" => "DNA"],
    	["code" => "403", "name" => "Huyện Như Thanh", "province_code" => "THO"],
    	["code" => "402", "name" => "Huyện Như Xuân", "province_code" => "THO"],
    	["code" => "299", "name" => "Huyện Ninh Giang", "province_code" => "HDU"],
    	["code" => "586", "name" => "Huyện Ninh Hải", "province_code" => "NTH"],
    	["code" => "587", "name" => "Huyện Ninh Phước", "province_code" => "NTH"],
    	["code" => "585", "name" => "Huyện Ninh Sơn", "province_code" => "NTH"],
    	["code" => "404", "name" => "Huyện Nông Cống", "province_code" => "THO"],
    	["code" => "519", "name" => "Huyện Nông Sơn", "province_code" => "QNA"],
    	["code" => "517", "name" => "Huyện Núi Thành", "province_code" => "QNA"],
    	["code" => "060", "name" => "Huyện Pác Nặm", "province_code" => "BKA"],
    	["code" => "476", "name" => "Huyện Phong Điền", "province_code" => "TTH"],
    	["code" => "926", "name" => "Huyện Phong Điền", "province_code" => "CTH"],
    	["code" => "109", "name" => "Huyện Phong Thổ", "province_code" => "LCH"],
    	["code" => "173", "name" => "Huyện Phú Bình", "province_code" => "TNG"],
    	["code" => "548", "name" => "Huyện Phù Cát", "province_code" => "BID"],
    	["code" => "333", "name" => "Huyện Phù Cừ", "province_code" => "HYE"],
    	["code" => "722", "name" => "Huyện Phú Giáo", "province_code" => "BDI"],
    	["code" => "563", "name" => "Huyện Phú Hoà", "province_code" => "PYE"],
    	["code" => "482", "name" => "Huyện Phú Lộc", "province_code" => "TTH"],
    	["code" => "168", "name" => "Huyện Phú Lương", "province_code" => "TNG"],
    	["code" => "545", "name" => "Huyện Phù Mỹ", "province_code" => "BID"],
    	["code" => "518", "name" => "Huyện Phú Ninh", "province_code" => "QNA"],
    	["code" => "233", "name" => "Huyện Phù Ninh", "province_code" => "PTO"],
    	["code" => "602", "name" => "Huyện Phú Quí", "province_code" => "BTH"],
    	["code" => "911", "name" => "Huyện Phú Quốc", "province_code" => "KGI"],
    	["code" => "698", "name" => "Huyện Phú Riềng", "province_code" => "BPH"],
    	["code" => "972", "name" => "Huyện Phú Tân", "province_code" => "CMA"],
    	["code" => "888", "name" => "Huyện Phú Tân", "province_code" => "AGI"],
    	["code" => "638", "name" => "Huyện Phú Thiện", "province_code" => "GLA"],
    	["code" => "478", "name" => "Huyện Phú Vang", "province_code" => "TTH"],
    	["code" => "280", "name" => "Huyện Phú Xuyên", "province_code" => "HNO"],
    	["code" => "122", "name" => "Huyện Phù Yên", "province_code" => "SLA"],
    	["code" => "050", "name" => "Huyện Phục Hoà", "province_code" => "CBA"],
    	["code" => "272", "name" => "Huyện Phúc Thọ", "province_code" => "HNO"],
    	["code" => "934", "name" => "Huyện Phụng Hiệp", "province_code" => "HUG"],
    	["code" => "957", "name" => "Huyện Phước Long", "province_code" => "BLI"],
    	["code" => "511", "name" => "Huyện Phước Sơn", "province_code" => "QNA"],
    	["code" => "029", "name" => "Huyện Quản Bạ", "province_code" => "HGI"],
    	["code" => "385", "name" => "Huyện Quan Hóa", "province_code" => "THO"],
    	["code" => "387", "name" => "Huyện Quan Sơn", "province_code" => "THO"],
    	["code" => "035", "name" => "Huyện Quang Bình", "province_code" => "HGI"],
    	["code" => "477", "name" => "Huyện Quảng Điền", "province_code" => "TTH"],
    	["code" => "456", "name" => "Huyện Quảng Ninh", "province_code" => "QBI"],
    	["code" => "454", "name" => "Huyện Quảng Trạch", "province_code" => "QBI"],
    	["code" => "049", "name" => "Huyện Quảng Uyên", "province_code" => "CBA"],
    	["code" => "406", "name" => "Huyện Quảng Xương", "province_code" => "THO"],
    	["code" => "415", "name" => "Huyện Quế Phong", "province_code" => "NAN"],
    	["code" => "509", "name" => "Huyện Quế Sơn", "province_code" => "QNA"],
    	["code" => "259", "name" => "Huyện Quế Võ", "province_code" => "BNI"],
    	["code" => "275", "name" => "Huyện Quốc Oai", "province_code" => "HNO"],
    	["code" => "416", "name" => "Huyện Quỳ Châu", "province_code" => "NAN"],
    	["code" => "420", "name" => "Huyện Quỳ Hợp", "province_code" => "NAN"],
    	["code" => "421", "name" => "Huyện Quỳnh Lưu", "province_code" => "NAN"],
    	["code" => "118", "name" => "Huyện Quỳnh Nhai", "province_code" => "SLA"],
    	["code" => "338", "name" => "Huyện Quỳnh Phụ", "province_code" => "TBI"],
    	["code" => "088", "name" => "Huyện Sa Pa", "province_code" => "LCA"],
    	["code" => "616", "name" => "Huyện Sa Thầy", "province_code" => "KON"],
    	["code" => "084", "name" => "Huyện Si Ma Cai", "province_code" => "LCA"],
    	["code" => "108", "name" => "Huyện Sìn Hồ", "province_code" => "LCH"],
    	["code" => "016", "name" => "Huyện Sóc Sơn", "province_code" => "HNO"],
    	["code" => "220", "name" => "Huyện Sơn Động", "province_code" => "BGI"],
    	["code" => "076", "name" => "Huyện Sơn Dương", "province_code" => "TQU"],
    	["code" => "529", "name" => "Huyện Sơn Hà", "province_code" => "QNG"],
    	["code" => "560", "name" => "Huyện Sơn Hòa", "province_code" => "PYE"],
    	["code" => "530", "name" => "Huyện Sơn Tây", "province_code" => "QNG"],
    	["code" => "527", "name" => "Huyện Sơn Tịnh", "province_code" => "QNG"],
    	["code" => "561", "name" => "Huyện Sông Hinh", "province_code" => "PYE"],
    	["code" => "253", "name" => "Huyện Sông Lô", "province_code" => "VPH"],
    	["code" => "126", "name" => "Huyện Sông Mã", "province_code" => "SLA"],
    	["code" => "127", "name" => "Huyện Sốp Cộp", "province_code" => "SLA"],
    	["code" => "860", "name" => "Huyện Tam Bình", "province_code" => "VLO"],
    	["code" => "248", "name" => "Huyện Tam Đảo", "province_code" => "VPH"],
    	["code" => "247", "name" => "Huyện Tam Dương", "province_code" => "VPH"],
    	["code" => "106", "name" => "Huyện Tam Đường", "province_code" => "LCH"],
    	["code" => "871", "name" => "Huyện Tam Nông", "province_code" => "DTH"],
    	["code" => "236", "name" => "Huyện Tam Nông", "province_code" => "PTO"],
    	["code" => "705", "name" => "Huyện Tân Biên", "province_code" => "TNI"],
    	["code" => "706", "name" => "Huyện Tân Châu", "province_code" => "TNI"],
    	["code" => "904", "name" => "Huyện Tân Hiệp", "province_code" => "KGI"],
    	["code" => "869", "name" => "Huyện Tân Hồng", "province_code" => "DTH"],
    	["code" => "796", "name" => "Huyện Tân Hưng", "province_code" => "LAN"],
    	["code" => "423", "name" => "Huyện Tân Kỳ", "province_code" => "NAN"],
    	["code" => "155", "name" => "Huyện Tân Lạc", "province_code" => "HBI"],
    	["code" => "734", "name" => "Huyện Tân Phú", "province_code" => "DNA"],
    	["code" => "825", "name" => "Huyện Tân Phú Đông", "province_code" => "TGI"],
    	["code" => "818", "name" => "Huyện Tân Phước", "province_code" => "TGI"],
    	["code" => "240", "name" => "Huyện Tân Sơn", "province_code" => "PTO"],
    	["code" => "754", "name" => "Huyện Tân Thành", "province_code" => "BRI"],
    	["code" => "799", "name" => "Huyện Tân Thạnh", "province_code" => "LAN"],
    	["code" => "805", "name" => "Huyện Tân Trụ", "province_code" => "LAN"],
    	["code" => "111", "name" => "Huyện Tân Uyên", "province_code" => "LCH"],
    	["code" => "216", "name" => "Huyện Tân Yên", "province_code" => "BGI"],
    	["code" => "599", "name" => "Huyện Tánh Linh", "province_code" => "BTH"],
    	["code" => "504", "name" => "Huyện Tây Giang", "province_code" => "QNA"],
    	["code" => "562", "name" => "Huyện Tây Hoà", "province_code" => "PYE"],
    	["code" => "547", "name" => "Huyện Tây Sơn", "province_code" => "BID"],
    	["code" => "526", "name" => "Huyện Tây Trà", "province_code" => "QNG"],
    	["code" => "053", "name" => "Huyện Thạch An", "province_code" => "CBA"],
    	["code" => "445", "name" => "Huyện Thạch Hà", "province_code" => "HTI"],
    	["code" => "391", "name" => "Huyện Thạch Thành", "province_code" => "THO"],
    	["code" => "276", "name" => "Huyện Thạch Thất", "province_code" => "HNO"],
    	["code" => "341", "name" => "Huyện Thái Thụy", "province_code" => "TBI"],
    	["code" => "110", "name" => "Huyện Than Uyên", "province_code" => "LCH"],
    	["code" => "513", "name" => "Huyện Thăng Bình", "province_code" => "QNA"],
    	["code" => "232", "name" => "Huyện Thanh Ba", "province_code" => "PTO"],
    	["code" => "874", "name" => "Huyện Thanh Bình", "province_code" => "DTH"],
    	["code" => "428", "name" => "Huyện Thanh Chương", "province_code" => "NAN"],
    	["code" => "294", "name" => "Huyện Thanh Hà", "province_code" => "HDU"],
    	["code" => "800", "name" => "Huyện Thạnh Hóa", "province_code" => "LAN"],
    	["code" => "351", "name" => "Huyện Thanh Liêm", "province_code" => "HNA"],
    	["code" => "300", "name" => "Huyện Thanh Miện", "province_code" => "HDU"],
    	["code" => "278", "name" => "Huyện Thanh Oai", "province_code" => "HNO"],
    	["code" => "837", "name" => "Huyện Thạnh Phú", "province_code" => "BTR"],
    	["code" => "238", "name" => "Huyện Thanh Sơn", "province_code" => "PTO"],
    	["code" => "239", "name" => "Huyện Thanh Thuỷ", "province_code" => "PTO"],
    	["code" => "020", "name" => "Huyện Thanh Trì", "province_code" => "HNO"],
    	["code" => "949", "name" => "Huyện Thạnh Trị", "province_code" => "STR"],
    	["code" => "872", "name" => "Huyện Tháp Mười", "province_code" => "DTH"],
    	["code" => "398", "name" => "Huyện Thiệu Hóa", "province_code" => "THO"],
    	["code" => "395", "name" => "Huyện Thọ Xuân", "province_code" => "THO"],
    	["code" => "894", "name" => "Huyện Thoại Sơn", "province_code" => "AGI"],
    	["code" => "967", "name" => "Huyện Thới Bình", "province_code" => "CMA"],
    	["code" => "927", "name" => "Huyện Thới Lai", "province_code" => "CTH"],
    	["code" => "738", "name" => "Huyện Thống Nhất", "province_code" => "DNA"],
    	["code" => "044", "name" => "Huyện Thông Nông", "province_code" => "CBA"],
    	["code" => "804", "name" => "Huyện Thủ Thừa", "province_code" => "LAN"],
    	["code" => "588", "name" => "Huyện Thuận Bắc", "province_code" => "NTH"],
    	["code" => "119", "name" => "Huyện Thuận Châu", "province_code" => "SLA"],
    	["code" => "589", "name" => "Huyện Thuận Nam", "province_code" => "NTH"],
    	["code" => "262", "name" => "Huyện Thuận Thành", "province_code" => "BNI"],
    	["code" => "279", "name" => "Huyện Thường Tín", "province_code" => "HNO"],
    	["code" => "396", "name" => "Huyện Thường Xuân", "province_code" => "THO"],
    	["code" => "311", "name" => "Huyện Thuỷ Nguyên", "province_code" => "HPO"],
    	["code" => "260", "name" => "Huyện Tiên Du", "province_code" => "BNI"],
    	["code" => "342", "name" => "Huyện Tiền Hải", "province_code" => "TBI"],
    	["code" => "315", "name" => "Huyện Tiên Lãng", "province_code" => "HPO"],
    	["code" => "332", "name" => "Huyện Tiên Lữ", "province_code" => "HYE"],
    	["code" => "514", "name" => "Huyện Tiên Phước", "province_code" => "QNA"],
    	["code" => "199", "name" => "Huyện Tiên Yên", "province_code" => "QNI"],
    	["code" => "846", "name" => "Huyện Tiểu Cần", "province_code" => "TVI"],
    	["code" => "890", "name" => "Huyện Tịnh Biên", "province_code" => "AGI"],
    	["code" => "407", "name" => "Huyện Tĩnh Gia", "province_code" => "THO"],
    	["code" => "525", "name" => "Huyện Trà Bồng", "province_code" => "QNG"],
    	["code" => "849", "name" => "Huyện Trà Cú", "province_code" => "TVI"],
    	["code" => "046", "name" => "Huyện Trà Lĩnh", "province_code" => "CBA"],
    	["code" => "862", "name" => "Huyện Trà Ôn", "province_code" => "VLO"],
    	["code" => "139", "name" => "Huyện Trạm Tấu", "province_code" => "YBA"],
    	["code" => "951", "name" => "Huyện Trần Đề", "province_code" => "STR"],
    	["code" => "968", "name" => "Huyện Trần Văn Thời", "province_code" => "CMA"],
    	["code" => "138", "name" => "Huyện Trấn Yên", "province_code" => "YBA"],
    	["code" => "712", "name" => "Huyện Trảng Bàng", "province_code" => "TNI"],
    	["code" => "737", "name" => "Huyện Trảng Bom", "province_code" => "DNA"],
    	["code" => "180", "name" => "Huyện Tràng Định", "province_code" => "LSO"],
    	["code" => "891", "name" => "Huyện Tri Tôn", "province_code" => "AGI"],
    	["code" => "469", "name" => "Huyện Triệu Phong", "province_code" => "QTI"],
    	["code" => "397", "name" => "Huyện Triệu Sơn", "province_code" => "THO"],
    	["code" => "363", "name" => "Huyện Trực Ninh", "province_code" => "NDI"],
    	["code" => "047", "name" => "Huyện Trùng Khánh", "province_code" => "CBA"],
    	["code" => "576", "name" => "Huyện Trường Sa", "province_code" => "KHO"],
    	["code" => "298", "name" => "Huyện Tứ Kỳ", "province_code" => "HDU"],
    	["code" => "617", "name" => "Huyện Tu Mơ Rông", "province_code" => "KON"],
    	["code" => "528", "name" => "Huyện Tư Nghĩa", "province_code" => "QNG"],
    	["code" => "098", "name" => "Huyện Tủa Chùa", "province_code" => "DBI"],
    	["code" => "099", "name" => "Huyện Tuần Giáo", "province_code" => "DBI"],
    	["code" => "418", "name" => "Huyện Tương Dương", "province_code" => "NAN"],
    	["code" => "559", "name" => "Huyện Tuy An", "province_code" => "PYE"],
    	["code" => "667", "name" => "Huyện Tuy Đức", "province_code" => "DKN"],
    	["code" => "595", "name" => "Huyện Tuy Phong", "province_code" => "BTH"],
    	["code" => "550", "name" => "Huyện Tuy Phước", "province_code" => "BID"],
    	["code" => "453", "name" => "Huyện Tuyên Hóa", "province_code" => "QBI"],
    	["code" => "966", "name" => "Huyện U Minh", "province_code" => "CMA"],
    	["code" => "913", "name" => "Huyện U Minh Thượng", "province_code" => "KGI"],
    	["code" => "281", "name" => "Huyện Ứng Hòa", "province_code" => "HNO"],
    	["code" => "089", "name" => "Huyện Văn Bàn", "province_code" => "LCA"],
    	["code" => "551", "name" => "Huyện Vân Canh", "province_code" => "BID"],
    	["code" => "140", "name" => "Huyện Văn Chấn", "province_code" => "YBA"],
    	["code" => "203", "name" => "Huyện Vân Đồn", "province_code" => "QNI"],
    	["code" => "326", "name" => "Huyện Văn Giang", "province_code" => "HYE"],
    	["code" => "128", "name" => "Huyện Vân Hồ", "province_code" => "SLA"],
    	["code" => "325", "name" => "Huyện Văn Lâm", "province_code" => "HYE"],
    	["code" => "182", "name" => "Huyện Văn Lãng", "province_code" => "LSO"],
    	["code" => "571", "name" => "Huyện Vạn Ninh", "province_code" => "KHO"],
    	["code" => "184", "name" => "Huyện Văn Quan", "province_code" => "LSO"],
    	["code" => "136", "name" => "Huyện Văn Yên", "province_code" => "YBA"],
    	["code" => "935", "name" => "Huyện Vị Thuỷ", "province_code" => "HUG"],
    	["code" => "030", "name" => "Huyện Vị Xuyên", "province_code" => "HGI"],
    	["code" => "222", "name" => "Huyện Việt Yên", "province_code" => "BGI"],
    	["code" => "316", "name" => "Huyện Vĩnh Bảo", "province_code" => "HPO"],
    	["code" => "735", "name" => "Huyện Vĩnh Cửu", "province_code" => "DNA"],
    	["code" => "797", "name" => "Huyện Vĩnh Hưng", "province_code" => "LAN"],
    	["code" => "464", "name" => "Huyện Vĩnh Linh", "province_code" => "QTI"],
    	["code" => "393", "name" => "Huyện Vĩnh Lộc", "province_code" => "THO"],
    	["code" => "958", "name" => "Huyện Vĩnh Lợi", "province_code" => "BLI"],
    	["code" => "924", "name" => "Huyện Vĩnh Thạnh", "province_code" => "CTH"],
    	["code" => "546", "name" => "Huyện Vĩnh Thạnh", "province_code" => "BID"],
    	["code" => "910", "name" => "Huyện Vĩnh Thuận", "province_code" => "KGI"],
    	["code" => "252", "name" => "Huyện Vĩnh Tường", "province_code" => "VPH"],
    	["code" => "170", "name" => "Huyện Võ Nhai", "province_code" => "TNG"],
    	["code" => "359", "name" => "Huyện Vụ Bản", "province_code" => "NDI"],
    	["code" => "441", "name" => "Huyện Vũ Quang", "province_code" => "HTI"],
    	["code" => "344", "name" => "Huyện Vũ Thư", "province_code" => "TBI"],
    	["code" => "033", "name" => "Huyện Xín Mần", "province_code" => "HGI"],
    	["code" => "741", "name" => "Huyện Xuân Lộc", "province_code" => "DNA"],
    	["code" => "364", "name" => "Huyện Xuân Trường", "province_code" => "NDI"],
    	["code" => "751", "name" => "Huyện Xuyên Mộc", "province_code" => "BRI"],
    	["code" => "360", "name" => "Huyện Ý Yên", "province_code" => "NDI"],
    	["code" => "141", "name" => "Huyện Yên Bình", "province_code" => "YBA"],
    	["code" => "124", "name" => "Huyện Yên Châu", "province_code" => "SLA"],
    	["code" => "394", "name" => "Huyện Yên Định", "province_code" => "THO"],
    	["code" => "221", "name" => "Huyện Yên Dũng", "province_code" => "BGI"],
    	["code" => "375", "name" => "Huyện Yên Khánh", "province_code" => "NBI"],
    	["code" => "251", "name" => "Huyện Yên Lạc", "province_code" => "VPH"],
    	["code" => "234", "name" => "Huyện Yên Lập", "province_code" => "PTO"],
    	["code" => "028", "name" => "Huyện Yên Minh", "province_code" => "HGI"],
    	["code" => "377", "name" => "Huyện Yên Mô", "province_code" => "NBI"],
    	["code" => "327", "name" => "Huyện Yên Mỹ", "province_code" => "HYE"],
    	["code" => "258", "name" => "Huyện Yên Phong", "province_code" => "BNI"],
    	["code" => "075", "name" => "Huyện Yên Sơn", "province_code" => "TQU"],
    	["code" => "426", "name" => "Huyện Yên Thành", "province_code" => "NAN"],
    	["code" => "215", "name" => "Huyện Yên Thế", "province_code" => "BGI"],
    	["code" => "158", "name" => "Huyện Yên Thủy", "province_code" => "HBI"],
    	["code" => "974", "name" => "Nước ngoài", "province_code" => "OVERSEA"],
    	["code" => "760", "name" => "Quận 1", "province_code" => "HCM"],
    	["code" => "771", "name" => "Quận 10", "province_code" => "HCM"],
    	["code" => "772", "name" => "Quận 11", "province_code" => "HCM"],
    	["code" => "761", "name" => "Quận 12", "province_code" => "HCM"],
    	["code" => "769", "name" => "Quận 2", "province_code" => "HCM"],
    	["code" => "770", "name" => "Quận 3", "province_code" => "HCM"],
    	["code" => "773", "name" => "Quận 4", "province_code" => "HCM"],
    	["code" => "774", "name" => "Quận 5", "province_code" => "HCM"],
    	["code" => "775", "name" => "Quận 6", "province_code" => "HCM"],
    	["code" => "778", "name" => "Quận 7", "province_code" => "HCM"],
    	["code" => "776", "name" => "Quận 8", "province_code" => "HCM"],
    	["code" => "763", "name" => "Quận 9", "province_code" => "HCM"],
    	["code" => "001", "name" => "Quận Ba Đình", "province_code" => "HNO"],
    	["code" => "021", "name" => "Quận Bắc Từ Liêm", "province_code" => "HNO"],
    	["code" => "777", "name" => "Quận Bình Tân", "province_code" => "HCM"],
    	["code" => "765", "name" => "Quận Bình Thạnh", "province_code" => "HCM"],
    	["code" => "918", "name" => "Quận Bình Thuỷ", "province_code" => "CTH"],
    	["code" => "919", "name" => "Quận Cái Răng", "province_code" => "CTH"],
    	["code" => "495", "name" => "Quận Cẩm Lệ", "province_code" => "DNG"],
    	["code" => "005", "name" => "Quận Cầu Giấy", "province_code" => "HNO"],
    	["code" => "308", "name" => "Quận Đồ Sơn", "province_code" => "HPO"],
    	["code" => "006", "name" => "Quận Đống Đa", "province_code" => "HNO"],
    	["code" => "309", "name" => "Quận Dương Kinh", "province_code" => "HPO"],
    	["code" => "764", "name" => "Quận Gò Vấp", "province_code" => "HCM"],
    	["code" => "268", "name" => "Quận Hà Đông", "province_code" => "HNO"],
    	["code" => "306", "name" => "Quận Hải An", "province_code" => "HPO"],
    	["code" => "007", "name" => "Quận Hai Bà Trưng", "province_code" => "HNO"],
    	["code" => "492", "name" => "Quận Hải Châu", "province_code" => "DNG"],
    	["code" => "002", "name" => "Quận Hoàn Kiếm", "province_code" => "HNO"],
    	["code" => "008", "name" => "Quận Hoàng Mai", "province_code" => "HNO"],
    	["code" => "303", "name" => "Quận Hồng Bàng", "province_code" => "HPO"],
    	["code" => "307", "name" => "Quận Kiến An", "province_code" => "HPO"],
    	["code" => "305", "name" => "Quận Lê Chân", "province_code" => "HPO"],
    	["code" => "490", "name" => "Quận Liên Chiểu", "province_code" => "DNG"],
    	["code" => "004", "name" => "Quận Long Biên", "province_code" => "HNO"],
    	["code" => "019", "name" => "Quận Nam Từ Liêm", "province_code" => "HNO"],
    	["code" => "304", "name" => "Quận Ngô Quyền", "province_code" => "HPO"],
    	["code" => "494", "name" => "Quận Ngũ Hành Sơn", "province_code" => "DNG"],
    	["code" => "916", "name" => "Quận Ninh Kiều", "province_code" => "CTH"],
    	["code" => "917", "name" => "Quận Ô Môn", "province_code" => "CTH"],
    	["code" => "768", "name" => "Quận Phú Nhuận", "province_code" => "HCM"],
    	["code" => "493", "name" => "Quận Sơn Trà", "province_code" => "DNG"],
    	["code" => "766", "name" => "Quận Tân Bình", "province_code" => "HCM"],
    	["code" => "767", "name" => "Quận Tân Phú", "province_code" => "HCM"],
    	["code" => "003", "name" => "Quận Tây Hồ", "province_code" => "HNO"],
    	["code" => "491", "name" => "Quận Thanh Khê", "province_code" => "DNG"],
    	["code" => "009", "name" => "Quận Thanh Xuân", "province_code" => "HNO"],
    	["code" => "923", "name" => "Quận Thốt Nốt", "province_code" => "CTH"],
    	["code" => "762", "name" => "Quận Thủ Đức", "province_code" => "HCM"],
    	["code" => "748", "name" => "Thành phố Bà Rịa", "province_code" => "BRI"],
    	["code" => "213", "name" => "Thành phố Bắc Giang", "province_code" => "BGI"],
    	["code" => "058", "name" => "Thành Phố Bắc Kạn", "province_code" => "BKA"],
    	["code" => "954", "name" => "Thành phố Bạc Liêu", "province_code" => "BLI"],
    	["code" => "256", "name" => "Thành phố Bắc Ninh", "province_code" => "BNI"],
    	["code" => "673", "name" => "Thành phố Bảo Lộc", "province_code" => "LDO"],
    	["code" => "829", "name" => "Thành phố Bến Tre", "province_code" => "BTR"],
    	["code" => "731", "name" => "Thành phố Biên Hòa", "province_code" => "DNA"],
    	["code" => "643", "name" => "Thành phố Buôn Ma Thuột", "province_code" => "DAK"],
    	["code" => "964", "name" => "Thành phố Cà Mau", "province_code" => "CMA"],
    	["code" => "195", "name" => "Thành phố Cẩm Phả", "province_code" => "QNI"],
    	["code" => "569", "name" => "Thành phố Cam Ranh", "province_code" => "KHO"],
    	["code" => "040", "name" => "Thành phố Cao Bằng", "province_code" => "CBA"],
    	["code" => "866", "name" => "Thành phố Cao Lãnh", "province_code" => "DTH"],
    	["code" => "884", "name" => "Thành phố Châu Đốc", "province_code" => "AGI"],
    	["code" => "672", "name" => "Thành phố Đà Lạt", "province_code" => "LDO"],
    	["code" => "094", "name" => "Thành phố Điện Biên Phủ", "province_code" => "DBI"],
    	["code" => "461", "name" => "Thành phố Đông Hà", "province_code" => "QTI"],
    	["code" => "450", "name" => "Thành Phố Đồng Hới", "province_code" => "QBI"],
    	["code" => "024", "name" => "Thành phố Hà Giang", "province_code" => "HGI"],
    	["code" => "193", "name" => "Thành phố Hạ Long", "province_code" => "QNI"],
    	["code" => "436", "name" => "Thành phố Hà Tĩnh", "province_code" => "HTI"],
    	["code" => "288", "name" => "Thành phố Hải Dương", "province_code" => "HDU"],
    	["code" => "148", "name" => "Thành phố Hòa Bình", "province_code" => "HBI"],
    	["code" => "503", "name" => "Thành phố Hội An", "province_code" => "QNA"],
    	["code" => "474", "name" => "Thành phố Huế", "province_code" => "TTH"],
    	["code" => "323", "name" => "Thành phố Hưng Yên", "province_code" => "HYE"],
    	["code" => "608", "name" => "Thành phố Kon Tum", "province_code" => "KON"],
    	["code" => "105", "name" => "Thành phố Lai Châu", "province_code" => "LCH"],
    	["code" => "178", "name" => "Thành phố Lạng Sơn", "province_code" => "LSO"],
    	["code" => "080", "name" => "Thành phố Lào Cai", "province_code" => "LCA"],
    	["code" => "883", "name" => "Thành phố Long Xuyên", "province_code" => "AGI"],
    	["code" => "194", "name" => "Thành phố Móng Cái", "province_code" => "QNI"],
    	["code" => "815", "name" => "Thành phố Mỹ Tho", "province_code" => "TGI"],
    	["code" => "356", "name" => "Thành phố Nam Định", "province_code" => "NDI"],
    	["code" => "568", "name" => "Thành phố Nha Trang", "province_code" => "KHO"],
    	["code" => "369", "name" => "Thành phố Ninh Bình", "province_code" => "NBI"],
    	["code" => "582", "name" => "Thành phố Phan Rang-Tháp Chàm", "province_code" => "NTH"],
    	["code" => "593", "name" => "Thành phố Phan Thiết", "province_code" => "BTH"],
    	["code" => "347", "name" => "Thành phố Phủ Lý", "province_code" => "HNA"],
    	["code" => "622", "name" => "Thành phố Pleiku", "province_code" => "GLA"],
    	["code" => "522", "name" => "Thành phố Quảng Ngãi", "province_code" => "QNG"],
    	["code" => "540", "name" => "Thành phố Qui Nhơn", "province_code" => "BID"],
    	["code" => "899", "name" => "Thành phố Rạch Giá", "province_code" => "KGI"],
    	["code" => "867", "name" => "Thành phố Sa Đéc", "province_code" => "DTH"],
    	["code" => "941", "name" => "Thành phố Sóc Trăng", "province_code" => "STR"],
    	["code" => "116", "name" => "Thành phố Sơn La", "province_code" => "SLA"],
    	["code" => "165", "name" => "Thành phố Sông Công", "province_code" => "TNG"],
    	["code" => "370", "name" => "Thành phố Tam Điệp", "province_code" => "NBI"],
    	["code" => "502", "name" => "Thành phố Tam Kỳ", "province_code" => "QNA"],
    	["code" => "794", "name" => "Thành phố Tân An", "province_code" => "LAN"],
    	["code" => "703", "name" => "Thành phố Tây Ninh", "province_code" => "TNI"],
    	["code" => "336", "name" => "Thành phố Thái Bình", "province_code" => "TBI"],
    	["code" => "164", "name" => "Thành phố Thái Nguyên", "province_code" => "TNG"],
    	["code" => "380", "name" => "Thành phố Thanh Hóa", "province_code" => "THO"],
    	["code" => "718", "name" => "Thành phố Thủ Dầu Một", "province_code" => "BDI"],
    	["code" => "842", "name" => "Thành phố Trà Vinh", "province_code" => "TVI"],
    	["code" => "555", "name" => "Thành phố Tuy Hoà", "province_code" => "PYE"],
    	["code" => "070", "name" => "Thành phố Tuyên Quang", "province_code" => "TQU"],
    	["code" => "196", "name" => "Thành phố Uông Bí", "province_code" => "QNI"],
    	["code" => "930", "name" => "Thành phố Vị Thanh", "province_code" => "HUG"],
    	["code" => "227", "name" => "Thành phố Việt Trì", "province_code" => "PTO"],
    	["code" => "412", "name" => "Thành phố Vinh", "province_code" => "NAN"],
    	["code" => "855", "name" => "Thành phố Vĩnh Long", "province_code" => "VLO"],
    	["code" => "243", "name" => "Thành phố Vĩnh Yên", "province_code" => "VPH"],
    	["code" => "747", "name" => "Thành phố Vũng Tàu", "province_code" => "BRI"],
    	["code" => "132", "name" => "Thành phố Yên Bái", "province_code" => "YBA"],
    	["code" => "623", "name" => "Thị xã An Khê", "province_code" => "GLA"],
    	["code" => "549", "name" => "Thị xã An Nhơn", "province_code" => "BID"],
    	["code" => "624", "name" => "Thị xã Ayun Pa", "province_code" => "GLA"],
    	["code" => "458", "name" => "Thị xã Ba Đồn", "province_code" => "QBI"],
    	["code" => "721", "name" => "Thị xã Bến Cát", "province_code" => "BDI"],
    	["code" => "381", "name" => "Thị xã Bỉm Sơn", "province_code" => "THO"],
    	["code" => "690", "name" => "Thị xã Bình Long", "province_code" => "BPH"],
    	["code" => "861", "name" => "Thị xã Bình Minh", "province_code" => "VLO"],
    	["code" => "644", "name" => "Thị Xã Buôn Hồ", "province_code" => "DAK"],
    	["code" => "817", "name" => "Thị xã Cai Lậy", "province_code" => "TGI"],
    	["code" => "290", "name" => "Thị xã Chí Linh", "province_code" => "HDU"],
    	["code" => "413", "name" => "Thị xã Cửa Lò", "province_code" => "NAN"],
    	["code" => "724", "name" => "Thị xã Dĩ An", "province_code" => "BDI"],
    	["code" => "507", "name" => "Thị xã Điện Bàn", "province_code" => "QNA"],
    	["code" => "205", "name" => "Thị xã Đông Triều", "province_code" => "QNI"],
    	["code" => "689", "name" => "Thị xã Đồng Xoài", "province_code" => "BPH"],
    	["code" => "851", "name" => "Thị xã Duyên Hải", "province_code" => "TVI"],
    	["code" => "660", "name" => "Thị xã Gia Nghĩa", "province_code" => "DKN"],
    	["code" => "959", "name" => "Thị xã Giá Rai", "province_code" => "BLI"],
    	["code" => "816", "name" => "Thị xã Gò Công", "province_code" => "TGI"],
    	["code" => "900", "name" => "Thị xã Hà Tiên", "province_code" => "KGI"],
    	["code" => "432", "name" => "Thị xã Hoàng Mai", "province_code" => "NAN"],
    	["code" => "437", "name" => "Thị xã Hồng Lĩnh", "province_code" => "HTI"],
    	["code" => "868", "name" => "Thị xã Hồng Ngự", "province_code" => "DTH"],
    	["code" => "479", "name" => "Thị xã Hương Thủy", "province_code" => "TTH"],
    	["code" => "480", "name" => "Thị xã Hương Trà", "province_code" => "TTH"],
    	["code" => "795", "name" => "Thị xã Kiến Tường", "province_code" => "LAN"],
    	["code" => "449", "name" => "Thị xã Kỳ Anh", "province_code" => "HTI"],
    	["code" => "594", "name" => "Thị xã La Gi", "province_code" => "BTH"],
    	["code" => "732", "name" => "Thị xã Long Khánh", "province_code" => "DNA"],
    	["code" => "937", "name" => "Thị xã Long Mỹ", "province_code" => "HUG"],
    	["code" => "095", "name" => "Thị Xã Mường Lay", "province_code" => "DBI"],
    	["code" => "931", "name" => "Thị xã Ngã Bảy", "province_code" => "HUG"],
    	["code" => "948", "name" => "Thị xã Ngã Năm", "province_code" => "STR"],
    	["code" => "133", "name" => "Thị xã Nghĩa Lộ", "province_code" => "YBA"],
    	["code" => "572", "name" => "Thị xã Ninh Hòa", "province_code" => "KHO"],
    	["code" => "172", "name" => "Thị xã Phổ Yên", "province_code" => "TNG"],
    	["code" => "228", "name" => "Thị xã Phú Thọ", "province_code" => "PTO"],
    	["code" => "244", "name" => "Thị xã Phúc Yên", "province_code" => "VPH"],
    	["code" => "688", "name" => "Thị xã Phước Long", "province_code" => "BPH"],
    	["code" => "462", "name" => "Thị xã Quảng Trị", "province_code" => "QTI"],
    	["code" => "206", "name" => "Thị xã Quảng Yên", "province_code" => "QNI"],
    	["code" => "382", "name" => "Thị xã Sầm Sơn", "province_code" => "THO"],
    	["code" => "269", "name" => "Thị xã Sơn Tây", "province_code" => "HNO"],
    	["code" => "557", "name" => "Thị xã Sông Cầu", "province_code" => "PYE"],
    	["code" => "887", "name" => "Thị xã Tân Châu", "province_code" => "AGI"],
    	["code" => "723", "name" => "Thị xã Tân Uyên", "province_code" => "BDI"],
    	["code" => "414", "name" => "Thị xã Thái Hoà", "province_code" => "NAN"],
    	["code" => "725", "name" => "Thị xã Thuận An", "province_code" => "BDI"],
    	["code" => "261", "name" => "Thị xã Từ Sơn", "province_code" => "BNI"],
    	["code" => "950", "name" => "Thị xã Vĩnh Châu", "province_code" => "STR"]];
    	DB::table('indemnity_districts')->insert($data);
    }
}
